modded class PluginRecipesManagerBase
{
	override void RegisterRecipies()
	{
		super.RegisterRecipies();
		// MVS
		UnregisterRecipe("CraftPatchAUS1");
		UnregisterRecipe("CraftPatchAUS2");
		UnregisterRecipe("CraftPatchCobra");
		UnregisterRecipe("CraftPatchGNR");
		UnregisterRecipe("CraftPatchMED");
		UnregisterRecipe("CraftPatchRFL");
		UnregisterRecipe("CraftPatchSL");
		UnregisterRecipe("CraftPatchSNPR");
		UnregisterRecipe("CraftPatchEOD");
		UnregisterRecipe("CraftPatchTL");
		UnregisterRecipe("CraftPatchUK1");
		UnregisterRecipe("CraftPatchUK2");
		UnregisterRecipe("CraftPatchUS1");
		UnregisterRecipe("CraftPatchUS2");
		UnregisterRecipe("CraftPatchCAN1");
		UnregisterRecipe("CraftPatchCAN2");
		//TF
		UnregisterRecipe("OpenZinkBox");
		UnregisterRecipe("OpenZinkBox762");
		UnregisterRecipe("TF_6B23_112Vest_EMR_Recipe");
		UnregisterRecipe("TF_6B23_112Vest_GFlora_Recipe");
		UnregisterRecipe("TF_6B43_EMR_6sh112_EMR_Recipe");
		UnregisterRecipe("TF_6B43_EMR_6sh112_Syrian_Recipe");
		UnregisterRecipe("TF_6B43_Syrian_6sh112_EMR_Recipe");
		UnregisterRecipe("TF_6B43_Syrian_6sh112_Syrian_Recipe");
		UnregisterRecipe("TF_6B23_112Vest_GFlora_Syrian_Recipe");
		UnregisterRecipe("TF_6B23_112Vest_EMR_Syrian_Recipe");
		//Quadlock
		UnregisterRecipe("riflesling_quad_black");
		UnregisterRecipe("riflesling_quad_green");
		UnregisterRecipe("riflesling_quad_tan");
		//MMG
		UnregisterRecipe("dismantle_equipment_locker_green");
		UnregisterRecipe("dismantle_equipment_locker_black");
		UnregisterRecipe("dismantle_equipment_locker_grey");
		UnregisterRecipe("dismantle_locker02_blue");
		UnregisterRecipe("dismantle_locker02_green");
		UnregisterRecipe("dismantle_locker02_tan");
		UnregisterRecipe("dismantle_mmg_gun_rack_blue");
		UnregisterRecipe("dismantle_mmg_gun_rack_green");
		UnregisterRecipe("dismantle_mmg_gun_rack_tan");
		UnregisterRecipe("dismantle_mmg_lockable_gun_rack_grey");
		UnregisterRecipe("dismantle_mmg_gun_rack_planks");
		UnregisterRecipe("dismantle_mmg_craftable_gun_rack");
		UnregisterRecipe("dismantle_mmg_gun_wall_wooden");
		UnregisterRecipe("dismantle_mmg_gun_wall_metal");
		UnregisterRecipe("dismantle_fridge_beige");
		UnregisterRecipe("dismantle_fridge_blue");
		UnregisterRecipe("dismantle_gear_stand");
		UnregisterRecipe("dismantle_mmg_craftable_tent");
		UnregisterRecipe("craft_mmg_crate03_unfinished_wood");
		UnregisterRecipe("craft_mmg_crate03_wood");
		UnregisterRecipe("craft_mmg_gun_wall_kit_wooden");
		UnregisterRecipe("craft_mmg_gun_wall_kit_metal");
		UnregisterRecipe("craft_mmg_gun_rack_planks");
		UnregisterRecipe("craft_mmg_craftable_gun_rack");
		UnregisterRecipe("craft_mmg_craftable_tent_kit");
		//Equipment System
		UnregisterRecipe("CraftHeavyGreen");
		UnregisterRecipe("CraftHeavyFlecktarn");
		UnregisterRecipe("CraftHeavyGrey");
		UnregisterRecipe("CraftHeavyMulticam");
		UnregisterRecipe("CraftHeavyTan");
		UnregisterRecipe("CraftHeavyUrban");
		UnregisterRecipe("CraftHeavyWD");
		UnregisterRecipe("CraftHeavyMARPAT");
		UnregisterRecipe("CraftHeavyUCP");
		UnregisterRecipe("CraftHeavyEMR");
		UnregisterRecipe("CraftHeavyNWU");
		UnregisterRecipe("UnpackSetNWU");
		UnregisterRecipe("UnpackSetEMR");
		UnregisterRecipe("UnpackSetMARPAT");
		UnregisterRecipe("UnpackSetUCP");
		UnregisterRecipe("ReloadingFilter");
	}
}