enum X18MedicalModifiers
{
	MDF_MEDIKIT_TIER1 = 54545,
	MDF_MEDIKIT_TIER2,
	MDF_MEDIKIT_TIER3,
	MDF_ENERGYSTALKER,
	MDF_MEXAMIN_INJECTOR,
	MDF_RADIOPROTECTANT,
	MDF_PC1,
	MDF_MEXAMIN,
	MDF_ANTIRADVODKA,
	MDF_ANTIRADJOINT,
	MDF_ANTIRADCIGARETTE
};